// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/ads/googleads/v20/services/campaign_SHARED_set_service.proto

package services

import (
	enums "google.golang.org/genproto/googleapis/ads/googleads/v20/enums"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v20/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [CampaignSHAREDSets][google.ads.googleads.v20.services.CampaignSHAREDSets].
type MutateCampaignSHAREDSetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose campaign SHARED sets are being
	// modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on individual campaign SHARED
	// sets.
	Operations []*CampaignSHAREDSetOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	// The response content type setting. Determines whether the mutable resource
	// or just the resource name should be returned post mutation.
	ResponseContentType enums.ResponseContentTypeEnum_ResponseContentType `protobuf:"varint,5,opt,name=response_content_type,json=responseContentType,proto3,enum=google.ads.googleads.v20.enums.ResponseContentTypeEnum_ResponseContentType" json:"response_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MutateCampaignSHAREDSetsRequest) Reset() {
	*x = MutateCampaignSHAREDSetsRequest{}
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignSHAREDSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignSHAREDSetsRequest) ProtoMessage() {}

func (x *MutateCampaignSHAREDSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignSHAREDSetsRequest.ProtoReflect.Descriptor instead.
func (*MutateCampaignSHAREDSetsRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateCampaignSHAREDSetsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateCampaignSHAREDSetOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *MutateCampaignSHAREDSetsRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *MutateCampaignSHAREDSetsRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

func (x *MutateCampaignSHAREDSetsRequest) GetResponseContentType() enums.ResponseContentTypeEnum_ResponseContentType {
	if x != nil {
		return x.ResponseContentType
	}
	return enums.ResponseContentTypeEnum_ResponseContentType(0)
}

// A single operation (create, remove) on a campaign SHARED set.
type CampaignSHAREDSetOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*CampaignSHAREDSetOperation_Create
	//	*CampaignSHAREDSetOperation_Remove
	Operation     isCampaignSHAREDSetOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignSHAREDSetOperation) Reset() {
	*x = CampaignSHAREDSetOperation{}
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignSHAREDSetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignSHAREDSetOperation) ProtoMessage() {}

func (x *CampaignSHAREDSetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignSHAREDSetOperation.ProtoReflect.Descriptor instead.
func (*CampaignSHAREDSetOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignSHAREDSetOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CampaignSHAREDSet {
	if x != nil {
		if x, ok := x.Operation.(*CampaignSHAREDSetOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *CampaignSHAREDSetOperation) GetRemove() string {
	if x != nil {
		if x, ok := x.Operation.(*CampaignSHAREDSetOperation_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

type isCampaignSHAREDSetOperation_Operation interface {
	isCampaignSHAREDSetOperation_Operation()
}

type CampaignSHAREDSetOperation_Create struct {
	// Create operation: No resource name is expected for the new campaign
	// SHARED set.
	Create *resources.CampaignSHAREDSet `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CampaignSHAREDSetOperation_Remove struct {
	// Remove operation: A resource name for the removed campaign SHARED set is
	// expected, in this format:
	//
	// `customers/{customer_id}/campaignSHARED_set_id}`
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*CampaignSHAREDSetOperation_Operation() {}

func (*CampaignSHAREDSetOperation_Operation() {}

// Response message for a campaign SHARED set mutate.
type MutateCampaignSHAREDSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	// Returned only when partial_failure = true and all errors occur inside the
	// operations. If any errors occur outside the operations (for example, auth
	// errors), we return an RPC level error.
	PartialFailureError *status.Status `protobuf:"bytes,3,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*MutateCampaignSHAREDSetResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCampaignSHAREDSetsResponse) Reset() {
	*x = MutateCampaignSHAREDSetsResponse{}
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignSHAREDSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignSHAREDSetsResponse) ProtoMessage() {}

func (x *MutateCampaignSHAREDSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignSHAREDSetsResponse.ProtoReflect.Descriptor instead.
func (*MutateCampaignSHAREDSetsResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateCampaignSHAREDSetsResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *MutateCampaignSHAREDSetResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the campaign SHARED set mutate.
type MutateCampaignSHAREDSetResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The mutated campaign SHARED set with only mutable fields after mutate. The
	// field will only be returned when response_content_type is set to
	// "MUTABLE_RESOURCE".
	CampaignSHAREDSet `protobuf:"bytes,2,opt,name=campaign_SHAREDSet,proto3" json:"campaign_SHARED_set,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MutateCampaignSHAREDSetResult) Reset() {
	*x = MutateCampaignSHAREDSetResult{}
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignSHAREDSetResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignSHAREDSetResult) ProtoMessage() {}

func (x *MutateCampaignSHAREDSetResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignSHAREDSetResult.ProtoReflect.Descriptor instead.
func (*MutateCampaignSHAREDSetResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateCampaignSHAREDSetResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *MutateCampaignSHAREDSet() *resources.CampaignSHAREDSet {
	if x != nil {
		return x.CampaignSHAREDSet
	}
	return nil
}

var File_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDesc = "" +
	"\n" +
	"Cgoogle/ads/googleads/v20/services/campaign_SHARED_set.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x17google/rpc/status.proto\"\xfa\x02\n" +
	"\x1fMutateCampaignSHAREDSetsRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12b\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2=.google.ads.googleads.v20.services.CampaignSHAREDSetOperationB\x03\xe0A\x02R\n" +
	"operations\x12'\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bR\x0epartialFailure\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\x12\x7f\n" +
	"\x15response_content_type\x18\x05 \x01(\x0e2K.google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentTypeR\x13responseContentType\"\xc5\x01\n" +
	"\x1aCampaignSHAREDSetOperation\x12O\n" +
	"\x06create\x18\x01 \x01(\v25.google.ads.googleads.v20.resources.CampaignSHAREDSetH\x00R\x06create\x12I\n" +
	"\x06remove\x18\x03 \x01(\tB/\xfaA,\n" +
	"*googleads.googleapis.com/CampaignSHAREDSetH\x00R\x06removeB\v\n" +
	"\toperation\"\xc6\x01\n" +
	" MutateCampaignSHAREDSetsResponse\x12F\n" +
	"\x15partial_failure_error\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12Z\n" +
	"\aresults\x18\x02 \x03(\v2@.google.ads.googleads.v20.services.MutateCampaignSHAREDSetResultR\aresults\"\xdc\x01\n" +
	"\x1dMutateCampaignSHAREDSetResult\x12T\n" +
	"\rresource_name\x18\x01 \x01(\tB/\xfaA,\n" +
	"*googleads.googleapis.com/CampaignSHAREDSetR\fresourceName\x12e\n" +
	"\x13campaign_SHAREDSetR\x11campaignSHAREDSet2\xe5\x02\n" +
	"\x18CampaignSHAREDSetService\x12\x81\x02\n" +
	"\x18MutateCampaignSHAREDSetsRequest\x1aC.google.ads.googleads.v20.services.MutateCampaignSHAREDSets:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x89\x02\n" +
	"%com.google.ads.googleads.v20.servicesB\x1dCampaignSHAREDSetServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v20/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V20.Services\xca\x02!Google\\Ads\\GoogleAds\\V20\\Services\xea\x02%Google::Ads::GoogleAds::V20::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDescData
}

var file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_goTypes = []any{
	(*MutateCampaignSHAREDSetsRequest
	(*CampaignSHAREDSetOperation
	(*MutateCampaignSHAREDSetsResponse
	(*MutateCampaignSHAREDSetResult
	(enums.ResponseContentTypeEnum_ResponseContentType)(0), // 4: google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	(*resources.CampaignSHAREDSet
	(*status.Status)(nil),                                  // 6: google.rpc.Status
}
var file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v20.services.MutateCampaignSHAREDSetOperation
	4, // 1: google.ads.googleads.v20.services.MutateCampaignSHAREDSetsRequest.response_content_type:type_name -> google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	5, // 2: google.ads.googleads.v20.services.CampaignSHAREDSet
	6, // 3: google.ads.googleads.v20.services.MutateCampaignSHAREDSetsResponse.partial_failure_error:type_name -> google.rpc.Status
	3, // 4: google.ads.googleads.v20.services.MutateCampaignSHAREDSetResult
	5, // 5: google.ads.googleads.v20.services.MutateCampaignSHARED_set:type_name -> google.ads.googleads.v20.resources.CampaignSHAREDSet
	0, // 6: google.ads.googleads.v20.services.CampaignSHAREDSets:input_type -> google.ads.googleads.v20.services.MutateCampaignSHAREDSetsRequest
	2, // 7: google.ads.googleads.v20.services.CampaignSHAREDSets:output_type -> google.ads.googleads.v20.services.MutateCampaignSHAREDSetsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_init() }
func file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_init() {
	if File_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto != nil {
		return
	}
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CampaignSHAREDSetOperation_Create)(nil),
		(*CampaignSHAREDSetOperation_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto = out.File
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_goTypes = nil
	file_google_ads_googleads_v20_services_campaign_SHARED_set_service_proto_depIdxs = nil
}
