// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/ads/googleads/v20/services/SHARED_criterion_service.proto

package services

import (
	enums "google.golang.org/genproto/googleapis/ads/googleads/v20/enums"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v20/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [SHAREDCriteria][google.ads.googleads.v20.services.SHAREDCriteria].
type MutateSHAREDCriteriaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose SHARED criteria are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on individual SHARED criteria.
	Operations []*SHAREDCriterionOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	// The response content type setting. Determines whether the mutable resource
	// or just the resource name should be returned post mutation.
	ResponseContentType enums.ResponseContentTypeEnum_ResponseContentType `protobuf:"varint,5,opt,name=response_content_type,json=responseContentType,proto3,enum=google.ads.googleads.v20.enums.ResponseContentTypeEnum_ResponseContentType" json:"response_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MutateSHAREDCriteriaRequest) Reset() {
	*x = MutateSHAREDCriteriaRequest{}
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateSHAREDCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateSHAREDCriteriaRequest) ProtoMessage() {}

func (x *MutateSHAREDCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateSHAREDCriteriaRequest.ProtoReflect.Descriptor instead.
func (*MutateSHAREDCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateSHAREDCriteriaRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateSHAREDCriterionOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *MutateSHAREDCriteriaRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *MutateSHAREDCriteriaRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

func (x *MutateSHAREDCriteriaRequest) GetResponseContentType() enums.ResponseContentTypeEnum_ResponseContentType {
	if x != nil {
		return x.ResponseContentType
	}
	return enums.ResponseContentTypeEnum_ResponseContentType(0)
}

// A single operation (create, remove) on an SHARED criterion.
type SHAREDCriterionOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*SHAREDCriterionOperation_Create
	//	*SHAREDCriterionOperation_Remove
	Operation     isSHAREDCriterionOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SHAREDCriterionOperation) Reset() {
	*x = SHAREDCriterionOperation{}
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SHAREDCriterionOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SHAREDCriterionOperation) ProtoMessage() {}

func (x *SHAREDCriterionOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SHAREDCriterionOperation.ProtoReflect.Descriptor instead.
func (*SHAREDCriterionOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescGZIP(), []int{1}
}

func (x *SHAREDCriterionOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *SHAREDCriterion {
	if x != nil {
		if x, ok := x.Operation.(*SHAREDCriterionOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *SHAREDCriterionOperation) GetRemove() string {
	if x != nil {
		if x, ok := x.Operation.(*SHAREDCriterionOperation_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

type isSHAREDCriterionOperation_Operation interface {
	isSHAREDCriterionOperation_Operation()
}

type SHAREDCriterionOperation_Create struct {
	// Create operation: No resource name is expected for the new SHARED
	// criterion.
	Create *resources.SHAREDCriterion `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type SHAREDCriterionOperation_Remove struct {
	// Remove operation: A resource name for the removed SHARED criterion is
	// expected, in this format:
	//
	// `customers/{customer_id}/SHARED_set_id}~{criterion_id}`
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*SHAREDCriterionOperation_Operation() {}

func (*SHAREDCriterionOperation_Operation() {}

// Response message for a SHARED criterion mutate.
type MutateSHAREDCriteriaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	// Returned only when partial_failure = true and all errors occur inside the
	// operations. If any errors occur outside the operations (for example, auth
	// errors), we return an RPC level error.
	PartialFailureError *status.Status `protobuf:"bytes,3,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*MutateSHAREDCriterionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateSHAREDCriteriaResponse) Reset() {
	*x = MutateSHAREDCriteriaResponse{}
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateSHAREDCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateSHAREDCriteriaResponse) ProtoMessage() {}

func (x *MutateSHAREDCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateSHAREDCriteriaResponse.ProtoReflect.Descriptor instead.
func (*MutateSHAREDCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateSHAREDCriteriaResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *MutateSHAREDCriterionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the SHARED criterion mutate.
type MutateSHAREDCriterionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The mutated SHARED criterion with only mutable fields after mutate. The
	// field will only be returned when response_content_type is set to
	// "MUTABLE_RESOURCE".
	SHAREDCriterion `protobuf:"bytes,2,opt,name=SHAREDCriterion,proto3" json:"SHARED_criterion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MutateSHAREDCriterionResult) Reset() {
	*x = MutateSHAREDCriterionResult{}
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateSHAREDCriterionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateSHAREDCriterionResult) ProtoMessage() {}

func (x *MutateSHAREDCriterionResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateSHAREDCriterionResult.ProtoReflect.Descriptor instead.
func (*MutateSHAREDCriterionResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateSHAREDCriterionResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *MutateSHAREDCriterion() *resources.SHAREDCriterion {
	if x != nil {
		return x.SHAREDCriterion
	}
	return nil
}

var File_google_ads_googleads_v20_services_SHARED_criterion_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDesc = "" +
	"\n" +
	"@google/ads/googleads/v20/services/SHARED_criterion.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x17google/rpc/status.proto\"\xf4\x02\n" +
	"\x1bMutateSHAREDCriteriaRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12`\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2;.google.ads.googleads.v20.services.SHAREDCriterionOperationB\x03\xe0A\x02R\n" +
	"operations\x12'\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bR\x0epartialFailure\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\x12\x7f\n" +
	"\x15response_content_type\x18\x05 \x01(\x0e2K.google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentTypeR\x13responseContentType\"\xbf\x01\n" +
	"\x18SHAREDCriterionOperation\x12M\n" +
	"\x06create\x18\x01 \x01(\v23.google.ads.googleads.v20.resources.SHAREDCriterionH\x00R\x06create\x12G\n" +
	"\x06remove\x18\x03 \x01(\tB-\xfaA*\n" +
	"(googleads.googleapis.com/SHAREDCriterionH\x00R\x06removeB\v\n" +
	"\toperation\"\xc0\x01\n" +
	"\x1cMutateSHAREDCriteriaResponse\x12F\n" +
	"\x15partial_failure_error\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12X\n" +
	"\aresults\x18\x02 \x03(\v2>.google.ads.googleads.v20.services.MutateSHAREDCriterionResultR\aresults\"\xd1\x01\n" +
	"\x1bMutateSHAREDCriterionResult\x12R\n" +
	"\rresource_name\x18\x01 \x01(\tB-\xfaA*\n" +
	"(googleads.googleapis.com/SHAREDCriterionR\fresourceName\x12^\n" +
	"\x10SHAREDCriterionR\x0fSHAREDCriterion2\xd3\x02\n" +
	"\x16SHAREDCriterionService\x12\xf1\x01\n" +
	"\x14MutateSHAREDCriteriaRequest\x1a?.google.ads.googleads.v20.services.MutateSHAREDCriteria:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x87\x02\n" +
	"%com.google.ads.googleads.v20.servicesB\x1bSHAREDCriterionServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v20/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V20.Services\xca\x02!Google\\Ads\\GoogleAds\\V20\\Services\xea\x02%Google::Ads::GoogleAds::V20::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDescData
}

var file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_goTypes = []any{
	(*MutateSHAREDCriteriaRequest
	(*SHAREDCriterionOperation
	(*MutateSHAREDCriteriaResponse
	(*MutateSHAREDCriterionResult
	(enums.ResponseContentTypeEnum_ResponseContentType)(0), // 4: google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	(*resources.SHAREDCriterion
	(*status.Status)(nil),                                  // 6: google.rpc.Status
}
var file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v20.services.MutateSHAREDCriterionOperation
	4, // 1: google.ads.googleads.v20.services.MutateSHAREDCriteriaRequest.response_content_type:type_name -> google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	5, // 2: google.ads.googleads.v20.services.SHAREDCriterion
	6, // 3: google.ads.googleads.v20.services.MutateSHAREDCriteriaResponse.partial_failure_error:type_name -> google.rpc.Status
	3, // 4: google.ads.googleads.v20.services.MutateSHAREDCriterionResult
	5, // 5: google.ads.googleads.v20.services.MutateSHARED_criterion:type_name -> google.ads.googleads.v20.resources.SHAREDCriterion
	0, // 6: google.ads.googleads.v20.services.SHAREDCriteria:input_type -> google.ads.googleads.v20.services.MutateSHAREDCriteriaRequest
	2, // 7: google.ads.googleads.v20.services.SHAREDCriteria:output_type -> google.ads.googleads.v20.services.MutateSHAREDCriteriaResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_init() }
func file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_init() {
	if File_google_ads_googleads_v20_services_SHARED_criterion_service_proto != nil {
		return
	}
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes[1].OneofWrappers = []any{
		(*SHAREDCriterionOperation_Create)(nil),
		(*SHAREDCriterionOperation_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_services_SHARED_criterion_service_proto = out.File
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_goTypes = nil
	file_google_ads_googleads_v20_services_SHARED_criterion_service_proto_depIdxs = nil
}
