// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/ads/googleads/v20/services/github.com/the-herald/monthly_reporter/reporter/shared_criterion_service.proto

package services

import (
	enums "google.golang.org/genproto/googleapis/ads/googleads/v20/enums"
	resources "google.golang.org/genproto/googleapis/ads/googleads/v20/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [github.com/the-herald/monthly_reporter/reporter/sharedCriteria][google.ads.googleads.v20.services.github.com/the-herald/monthly_reporter/reporter/sharedCriteria].
type Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose github.com/the-herald/monthly_reporter/reporter/shared criteria are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on individual github.com/the-herald/monthly_reporter/reporter/shared criteria.
	Operations []*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// If true, the request is validated but not executed. Only errors are
	// returned, not results.
	ValidateOnly bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	// The response content type setting. Determines whether the mutable resource
	// or just the resource name should be returned post mutation.
	ResponseContentType enums.ResponseContentTypeEnum_ResponseContentType `protobuf:"varint,5,opt,name=response_content_type,json=responseContentType,proto3,enum=google.ads.googleads.v20.enums.ResponseContentTypeEnum_ResponseContentType" json:"response_content_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) Reset() {
	*x = Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest{}
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) ProtoMessage() {}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest.ProtoReflect.Descriptor instead.
func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescGZIP(), []int{0}
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest) GetResponseContentType() enums.ResponseContentTypeEnum_ResponseContentType {
	if x != nil {
		return x.ResponseContentType
	}
	return enums.ResponseContentTypeEnum_ResponseContentType(0)
}

// A single operation (create, remove) on an github.com/the-herald/monthly_reporter/reporter/shared criterion.
type github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Create
	//	*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Remove
	Operation     isgithub.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) Reset() {
	*x = github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation{}
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) ProtoMessage() {}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation.ProtoReflect.Descriptor instead.
func (*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescGZIP(), []int{1}
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterion {
	if x != nil {
		if x, ok := x.Operation.(*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation) GetRemove() string {
	if x != nil {
		if x, ok := x.Operation.(*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

type isgithub.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation interface {
	isgithub.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation()
}

type github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Create struct {
	// Create operation: No resource name is expected for the new github.com/the-herald/monthly_reporter/reporter/shared
	// criterion.
	Create *resources.github.com/the-herald/monthly_reporter/reporter/sharedCriterion `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Remove struct {
	// Remove operation: A resource name for the removed github.com/the-herald/monthly_reporter/reporter/shared criterion is
	// expected, in this format:
	//
	// `customers/{customer_id}/github.com/the-herald/monthly_reporter/reporter/shared_set_id}~{criterion_id}`
	Remove string `protobuf:"bytes,3,opt,name=remove,proto3,oneof"`
}

func (*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation() {}

func (*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Operation() {}

// Response message for a github.com/the-herald/monthly_reporter/reporter/shared criterion mutate.
type Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	// Returned only when partial_failure = true and all errors occur inside the
	// operations. If any errors occur outside the operations (for example, auth
	// errors), we return an RPC level error.
	PartialFailureError *status.Status `protobuf:"bytes,3,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) Reset() {
	*x = Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse{}
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) ProtoMessage() {}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse.ProtoReflect.Descriptor instead.
func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescGZIP(), []int{2}
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the github.com/the-herald/monthly_reporter/reporter/shared criterion mutate.
type Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// The mutated github.com/the-herald/monthly_reporter/reporter/shared criterion with only mutable fields after mutate. The
	// field will only be returned when response_content_type is set to
	// "MUTABLE_RESOURCE".
	github.com/the-herald/monthly_reporter/reporter/sharedCriterion `protobuf:"bytes,2,opt,name=github.com/the-herald/monthly_reporter/reporter/sharedCriterion,proto3" json:"github.com/the-herald/monthly_reporter/reporter/shared_criterion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) Reset() {
	*x = Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult{}
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) ProtoMessage() {}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult.ProtoReflect.Descriptor instead.
func (*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescGZIP(), []int{3}
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterion() *resources.github.com/the-herald/monthly_reporter/reporter/sharedCriterion {
	if x != nil {
		return x.github.com/the-herald/monthly_reporter/reporter/sharedCriterion
	}
	return nil
}

var File_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDesc = "" +
	"\n" +
	"@google/ads/googleads/v20/services/github.com/the-herald/monthly_reporter/reporter/shared_criterion.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a\x17google/rpc/status.proto\"\xf4\x02\n" +
	"\x1bMutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12`\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2;.google.ads.googleads.v20.services.github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperationB\x03\xe0A\x02R\n" +
	"operations\x12'\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bR\x0epartialFailure\x12#\n" +
	"\rvalidate_only\x18\x04 \x01(\bR\fvalidateOnly\x12\x7f\n" +
	"\x15response_content_type\x18\x05 \x01(\x0e2K.google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentTypeR\x13responseContentType\"\xbf\x01\n" +
	"\x18github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation\x12M\n" +
	"\x06create\x18\x01 \x01(\v23.google.ads.googleads.v20.resources.github.com/the-herald/monthly_reporter/reporter/sharedCriterionH\x00R\x06create\x12G\n" +
	"\x06remove\x18\x03 \x01(\tB-\xfaA*\n" +
	"(googleads.googleapis.com/github.com/the-herald/monthly_reporter/reporter/sharedCriterionH\x00R\x06removeB\v\n" +
	"\toperation\"\xc0\x01\n" +
	"\x1cMutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse\x12F\n" +
	"\x15partial_failure_error\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12X\n" +
	"\aresults\x18\x02 \x03(\v2>.google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResultR\aresults\"\xd1\x01\n" +
	"\x1bMutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult\x12R\n" +
	"\rresource_name\x18\x01 \x01(\tB-\xfaA*\n" +
	"(googleads.googleapis.com/github.com/the-herald/monthly_reporter/reporter/sharedCriterionR\fresourceName\x12^\n" +
	"\x10github.com/the-herald/monthly_reporter/reporter/sharedCriterionR\x0fgithub.com/the-herald/monthly_reporter/reporter/sharedCriterion2\xd3\x02\n" +
	"\x16github.com/the-herald/monthly_reporter/reporter/sharedCriterionService\x12\xf1\x01\n" +
	"\x14Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest\x1a?.google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteria:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x87\x02\n" +
	"%com.google.ads.googleads.v20.servicesB\x1bgithub.com/the-herald/monthly_reporter/reporter/sharedCriterionServiceProtoP\x01ZIgoogle.golang.org/genproto/googleapis/ads/googleads/v20/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V20.Services\xca\x02!Google\\Ads\\GoogleAds\\V20\\Services\xea\x02%Google::Ads::GoogleAds::V20::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDesc), len(file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDescData
}

var file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_goTypes = []any{
	(*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest
	(*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation
	(*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse
	(*Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult
	(enums.ResponseContentTypeEnum_ResponseContentType)(0), // 4: google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	(*resources.github.com/the-herald/monthly_reporter/reporter/sharedCriterion
	(*status.Status)(nil),                                  // 6: google.rpc.Status
}
var file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation
	4, // 1: google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest.response_content_type:type_name -> google.ads.googleads.v20.enums.ResponseContentTypeEnum.ResponseContentType
	5, // 2: google.ads.googleads.v20.services.github.com/the-herald/monthly_reporter/reporter/sharedCriterion
	6, // 3: google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse.partial_failure_error:type_name -> google.rpc.Status
	3, // 4: google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriterionResult
	5, // 5: google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/shared_criterion:type_name -> google.ads.googleads.v20.resources.github.com/the-herald/monthly_reporter/reporter/sharedCriterion
	0, // 6: google.ads.googleads.v20.services.github.com/the-herald/monthly_reporter/reporter/sharedCriteria:input_type -> google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaRequest
	2, // 7: google.ads.googleads.v20.services.github.com/the-herald/monthly_reporter/reporter/sharedCriteria:output_type -> google.ads.googleads.v20.services.Mutategithub.com/the-herald/monthly_reporter/reporter/sharedCriteriaResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_init() }
func file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_init() {
	if File_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto != nil {
		return
	}
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes[1].OneofWrappers = []any{
		(*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Create)(nil),
		(*github.com/the-herald/monthly_reporter/reporter/sharedCriterionOperation_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto = out.File
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_goTypes = nil
	file_google_ads_googleads_v20_services_github.com/the-herald/monthly_reporter/reporter/shared_criterion_service_proto_depIdxs = nil
}

