// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/ads/googleads/v20/errors/github.com/the-herald/monthly_reporter/reporter/shared_set_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible github.com/the-herald/monthly_reporter/reporter/shared set errors.
type github.com/the-herald/monthly_reporter/reporter/sharedSetError int32

const (
	// Enum unspecified.
	github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum_github.com/the-herald/monthly_reporter/reporter/sharedSetError = 0
	// The received error code is not known in this version.
	github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum_github.com/the-herald/monthly_reporter/reporter/sharedSetError = 1
	// The customer cannot create this type of github.com/the-herald/monthly_reporter/reporter/shared set.
	github.com/the-herald/monthly_reporter/reporter/shared_SET_OF_THIS_TYPE github.com/the-herald/monthly_reporter/reporter/sharedSetError = 2
	// A github.com/the-herald/monthly_reporter/reporter/shared set with this name already exists.
	github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum_github.com/the-herald/monthly_reporter/reporter/sharedSetError = 3
	// Removed github.com/the-herald/monthly_reporter/reporter/shared sets cannot be mutated.
	github.com/the-herald/monthly_reporter/reporter/shared_SET_REMOVED github.com/the-herald/monthly_reporter/reporter/sharedSetError = 4
	// The github.com/the-herald/monthly_reporter/reporter/shared set cannot be removed because it is in use.
	github.com/the-herald/monthly_reporter/reporter/shared_SET_IN_USE github.com/the-herald/monthly_reporter/reporter/sharedSetError = 5
)

// Enum value maps for github.com/the-herald/monthly_reporter/reporter/sharedSetError.
var (
	github.com/the-herald/monthly_reporter/reporter/sharedSetError_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "CUSTOMER_CANNOT_CREATE_github.com/the-herald/monthly_reporter/reporter/shared_SET_OF_THIS_TYPE",
		3: "DUPLICATE_NAME",
		4: "github.com/the-herald/monthly_reporter/reporter/shared_SET_REMOVED",
		5: "github.com/the-herald/monthly_reporter/reporter/shared_SET_IN_USE",
	}
	github.com/the-herald/monthly_reporter/reporter/sharedSetError_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"CUSTOMER_CANNOT_CREATE_github.com/the-herald/monthly_reporter/reporter/shared_SET_OF_THIS_TYPE": 2,
		"DUPLICATE_NAME":     3,
		"github.com/the-herald/monthly_reporter/reporter/shared_SET_REMOVED": 4,
		"github.com/the-herald/monthly_reporter/reporter/shared_SET_IN_USE":  5,
	}
)

func (x github.com/the-herald/monthly_reporter/reporter/sharedSetError) Enum() *github.com/the-herald/monthly_reporter/reporter/sharedSetError {
	p := new(github.com/the-herald/monthly_reporter/reporter/sharedSetError)
	*p = x
	return p
}

func (x github.com/the-herald/monthly_reporter/reporter/sharedSetError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (github.com/the-herald/monthly_reporter/reporter/sharedSetError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_enumTypes[0].Descriptor()
}

func (github.com/the-herald/monthly_reporter/reporter/sharedSetError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_enumTypes[0]
}

func (x github.com/the-herald/monthly_reporter/reporter/sharedSetError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use github.com/the-herald/monthly_reporter/reporter/sharedSetError.Descriptor instead.
func (github.com/the-herald/monthly_reporter/reporter/sharedSetError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible github.com/the-herald/monthly_reporter/reporter/shared set errors.
type github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum) Reset() {
	*x = github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum{}
	mi := &file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum) ProtoMessage() {}

func (x *github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum.ProtoReflect.Descriptor instead.
func (*github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDesc = "" +
	"\n" +
	"6google/ads/googleads/v20/errors/github.com/the-herald/monthly_reporter/reporter/shared_set_error.proto\x12\x1fgoogle.ads.googleads.v20.errors\"\xbc\x01\n" +
	"\x12github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum\"\xa5\x01\n" +
	"\x0egithub.com/the-herald/monthly_reporter/reporter/sharedSetError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x122\n" +
	".CUSTOMER_CANNOT_CREATE_github.com/the-herald/monthly_reporter/reporter/shared_SET_OF_THIS_TYPE\x10\x02\x12\x12\n" +
	"\x0eDUPLICATE_NAME\x10\x03\x12\x16\n" +
	"\x12github.com/the-herald/monthly_reporter/reporter/shared_SET_REMOVED\x10\x04\x12\x15\n" +
	"\x11github.com/the-herald/monthly_reporter/reporter/shared_SET_IN_USE\x10\x05B\xf3\x01\n" +
	"#com.google.ads.googleads.v20.errorsB\x13github.com/the-herald/monthly_reporter/reporter/sharedSetErrorProtoP\x01ZEgoogle.golang.org/genproto/googleapis/ads/googleads/v20/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V20.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V20\\Errors\xea\x02#Google::Ads::GoogleAds::V20::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDesc), len(file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDescData
}

var file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_goTypes = []any{
	(github.com/the-herald/monthly_reporter/reporter/sharedSetError)(0), // 0: google.ads.googleads.v20.errors.github.com/the-herald/monthly_reporter/reporter/sharedSetError
	(*github.com/the-herald/monthly_reporter/reporter/sharedSetErrorEnum
}
var file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_init() }
func file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_init() {
	if File_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto = out.File
	file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_goTypes = nil
	file_google_ads_googleads_v20_errors_github.com/the-herald/monthly_reporter/reporter/shared_set_error_proto_depIdxs = nil
}

